package zeitvertreib.economy.sell;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

import java.util.Map;

public final class ItemSellPriceRegistry {

    public static final Map<Item, Integer> BASE_PRICES = Map.ofEntries(
        // --- Tier 1: Trivial (1 coin) - Unlimited/Early Game ---
        Map.entry(Items.WHEAT, 1),
        Map.entry(Items.CARROT, 1),
        Map.entry(Items.POTATO, 1),
        Map.entry(Items.BEETROOT, 1),
        Map.entry(Items.SUGAR_CANE, 1),
        Map.entry(Items.PUMPKIN, 1),
        Map.entry(Items.MELON_SLICE, 1),
        Map.entry(Items.BAMBOO, 1),
        Map.entry(Items.SWEET_BERRIES, 1),
        Map.entry(Items.GLOW_BERRIES, 1),
        Map.entry(Items.KELP, 1),
        Map.entry(Items.SEAGRASS, 1),
        Map.entry(Items.PAPER, 1),
        Map.entry(Items.SUGAR, 1),
        Map.entry(Items.COBBLESTONE, 1),
        Map.entry(Items.STONE, 1),
        Map.entry(Items.GRAVEL, 1),
        Map.entry(Items.SAND, 1),
        Map.entry(Items.RED_SAND, 1),
        Map.entry(Items.DIRT, 1),
        Map.entry(Items.ROOTED_DIRT, 1),
        Map.entry(Items.TUFF, 1),
        Map.entry(Items.NETHERRACK, 1),
        Map.entry(Items.BLACKSTONE, 1),
        Map.entry(Items.BASALT, 1),
        Map.entry(Items.END_STONE, 1),
        Map.entry(Items.EGG, 1),
        Map.entry(Items.ROTTEN_FLESH, 1),
        Map.entry(Items.BONE_MEAL, 1),

        // --- Seeds (1 coin) ---
        Map.entry(Items.WHEAT_SEEDS, 1),
        Map.entry(Items.BEETROOT_SEEDS, 1),
        Map.entry(Items.PUMPKIN_SEEDS, 1),
        Map.entry(Items.MELON_SEEDS, 1),

        // --- Saplings (1–2 coins) ---
        Map.entry(Items.OAK_SAPLING, 1),
        Map.entry(Items.SPRUCE_SAPLING, 1),
        Map.entry(Items.BIRCH_SAPLING, 1),
        Map.entry(Items.JUNGLE_SAPLING, 1),
        Map.entry(Items.ACACIA_SAPLING, 1),
        Map.entry(Items.DARK_OAK_SAPLING, 1),
        Map.entry(Items.MANGROVE_PROPAGULE, 1),
        Map.entry(Items.CHERRY_SAPLING, 1),
        Map.entry(Items.PALE_OAK_SAPLING, 1),

        // --- Mushrooms & Fungi (1–2 coins) ---
        Map.entry(Items.RED_MUSHROOM, 1),
        Map.entry(Items.BROWN_MUSHROOM, 1),
        Map.entry(Items.RED_MUSHROOM_BLOCK, 2),
        Map.entry(Items.BROWN_MUSHROOM_BLOCK, 2),
        Map.entry(Items.MUSHROOM_STEM, 1),
        Map.entry(Items.WARPED_FUNGUS, 2),
        Map.entry(Items.CRIMSON_FUNGUS, 2),

        // --- Blocks & Decoratives (1–3 coins) ---
        Map.entry(Items.HAY_BLOCK, 2),
        Map.entry(Items.SLIME_BLOCK, 3),
        Map.entry(Items.MOSS_BLOCK, 1),
        Map.entry(Items.MOSS_CARPET, 1),
        Map.entry(Items.SMALL_DRIPLEAF, 1),
        Map.entry(Items.BIG_DRIPLEAF, 2),
        Map.entry(Items.HANGING_ROOTS, 1),
        Map.entry(Items.SPORE_BLOSSOM, 2),
        Map.entry(Items.SCULK, 4),
        Map.entry(Items.SCULK_SENSOR, 6),
        Map.entry(Items.CALIBRATED_SCULK_SENSOR, 8),
        Map.entry(Items.SCULK_CATALYST, 15),
        Map.entry(Items.SCULK_VEIN, 2),

        // --- Copper Variants (2–8 coins) ---
        Map.entry(Items.CUT_COPPER, 2),
        Map.entry(Items.WAXED_COPPER_BLOCK, 2),
        Map.entry(Items.WAXED_CUT_COPPER, 2),
        Map.entry(Items.EXPOSED_COPPER, 2),
        Map.entry(Items.WEATHERED_COPPER, 2),
        Map.entry(Items.OXIDIZED_COPPER, 2),

        // --- Stone Variants (1–3 coins) ---
        Map.entry(Items.COBBLED_DEEPSLATE, 1),
        Map.entry(Items.DEEPSLATE, 1),
        Map.entry(Items.DEEPSLATE_BRICKS, 1),
        Map.entry(Items.CRACKED_DEEPSLATE_BRICKS, 1),
        Map.entry(Items.DEEPSLATE_TILES, 1),
        Map.entry(Items.CRACKED_DEEPSLATE_TILES, 1),
        Map.entry(Items.STONE_BRICKS, 1),
        Map.entry(Items.CRACKED_STONE_BRICKS, 1),
        Map.entry(Items.MOSSY_STONE_BRICKS, 1),
        Map.entry(Items.CHISELED_STONE_BRICKS, 1),
        Map.entry(Items.SMOOTH_STONE, 1),
        Map.entry(Items.ANDESITE, 1),
        Map.entry(Items.DIORITE, 1),
        Map.entry(Items.GRANITE, 1),
        Map.entry(Items.POLISHED_ANDESITE, 1),
        Map.entry(Items.POLISHED_DIORITE, 1),
        Map.entry(Items.POLISHED_GRANITE, 1),

        // --- Wooden Items (1 coin) ---
        Map.entry(Items.OAK_DOOR, 1),
        Map.entry(Items.SPRUCE_DOOR, 1),
        Map.entry(Items.BIRCH_DOOR, 1),
        Map.entry(Items.JUNGLE_DOOR, 1),
        Map.entry(Items.ACACIA_DOOR, 1),
        Map.entry(Items.DARK_OAK_DOOR, 1),
        Map.entry(Items.MANGROVE_DOOR, 1),
        Map.entry(Items.CHERRY_DOOR, 1),
        Map.entry(Items.PALE_OAK_DOOR, 1),
        Map.entry(Items.OAK_TRAPDOOR, 1),
        Map.entry(Items.SPRUCE_TRAPDOOR, 1),
        Map.entry(Items.BIRCH_TRAPDOOR, 1),
        Map.entry(Items.JUNGLE_TRAPDOOR, 1),
        Map.entry(Items.ACACIA_TRAPDOOR, 1),
        Map.entry(Items.DARK_OAK_TRAPDOOR, 1),
        Map.entry(Items.MANGROVE_TRAPDOOR, 1),
        Map.entry(Items.CHERRY_TRAPDOOR, 1),
        Map.entry(Items.PALE_OAK_TRAPDOOR, 1),
        Map.entry(Items.OAK_FENCE, 1),
        Map.entry(Items.SPRUCE_FENCE, 1),
        Map.entry(Items.BIRCH_FENCE, 1),
        Map.entry(Items.JUNGLE_FENCE, 1),
        Map.entry(Items.ACACIA_FENCE, 1),
        Map.entry(Items.DARK_OAK_FENCE, 1),
        Map.entry(Items.MANGROVE_FENCE, 1),
        Map.entry(Items.CHERRY_FENCE, 1),
        Map.entry(Items.PALE_OAK_FENCE, 1),
        Map.entry(Items.OAK_FENCE_GATE, 1),
        Map.entry(Items.SPRUCE_FENCE_GATE, 1),
        Map.entry(Items.BIRCH_FENCE_GATE, 1),
        Map.entry(Items.JUNGLE_FENCE_GATE, 1),
        Map.entry(Items.ACACIA_FENCE_GATE, 1),
        Map.entry(Items.DARK_OAK_FENCE_GATE, 1),
        Map.entry(Items.MANGROVE_FENCE_GATE, 1),
        Map.entry(Items.CHERRY_FENCE_GATE, 1),
        Map.entry(Items.PALE_OAK_FENCE_GATE, 1),
        Map.entry(Items.LADDER, 1),

        // --- Tier 2: Common (2–3 coins) - Easy to Acquire ---
        Map.entry(Items.OAK_LOG, 4),
        Map.entry(Items.SPRUCE_LOG, 4),
        Map.entry(Items.BIRCH_LOG, 4),
        Map.entry(Items.JUNGLE_LOG, 4),
        Map.entry(Items.ACACIA_LOG, 4),
        Map.entry(Items.DARK_OAK_LOG, 4),
        Map.entry(Items.MANGROVE_LOG, 4),
        Map.entry(Items.CHERRY_LOG, 4),
        Map.entry(Items.PALE_OAK_LOG, 4),
        Map.entry(Items.STRIPPED_OAK_LOG, 4),
        Map.entry(Items.OAK_WOOD, 3),
        Map.entry(Items.SPRUCE_WOOD, 3),
        Map.entry(Items.BIRCH_WOOD, 3),
        Map.entry(Items.JUNGLE_WOOD, 3),
        Map.entry(Items.ACACIA_WOOD, 3),
        Map.entry(Items.DARK_OAK_WOOD, 3),
        Map.entry(Items.MANGROVE_WOOD, 3),
        Map.entry(Items.CHERRY_WOOD, 3),
        Map.entry(Items.PALE_OAK_WOOD, 3),
        Map.entry(Items.STRIPPED_OAK_WOOD, 3),
        Map.entry(Items.COCOA_BEANS, 2),
        Map.entry(Items.NETHER_WART, 2),
        Map.entry(Items.APPLE, 2),
        Map.entry(Items.DRIED_KELP, 2),
        Map.entry(Items.POINTED_DRIPSTONE, 2),
        Map.entry(Items.WHITE_WOOL, 2),
        Map.entry(Items.ORANGE_WOOL, 2),
        Map.entry(Items.MAGENTA_WOOL, 2),
        Map.entry(Items.LIGHT_BLUE_WOOL, 2),
        Map.entry(Items.YELLOW_WOOL, 2),
        Map.entry(Items.LIME_WOOL, 2),
        Map.entry(Items.PINK_WOOL, 2),
        Map.entry(Items.GRAY_WOOL, 2),
        Map.entry(Items.LIGHT_GRAY_WOOL, 2),
        Map.entry(Items.CYAN_WOOL, 2),
        Map.entry(Items.PURPLE_WOOL, 2),
        Map.entry(Items.BLUE_WOOL, 2),
        Map.entry(Items.BROWN_WOOL, 2),
        Map.entry(Items.GREEN_WOOL, 2),
        Map.entry(Items.RED_WOOL, 2),
        Map.entry(Items.BLACK_WOOL, 2),
        Map.entry(Items.FLINT, 2),
        Map.entry(Items.CLAY_BALL, 2),
        Map.entry(Items.COAL, 2),
        Map.entry(Items.CALCITE, 2),
        Map.entry(Items.DRIPSTONE_BLOCK, 2),
        Map.entry(Items.WHITE_DYE, 2),
        Map.entry(Items.ORANGE_DYE, 2),
        Map.entry(Items.MAGENTA_DYE, 2),
        Map.entry(Items.LIGHT_BLUE_DYE, 2),
        Map.entry(Items.YELLOW_DYE, 2),
        Map.entry(Items.LIME_DYE, 2),
        Map.entry(Items.PINK_DYE, 2),
        Map.entry(Items.GRAY_DYE, 2),
        Map.entry(Items.LIGHT_GRAY_DYE, 2),
        Map.entry(Items.CYAN_DYE, 2),
        Map.entry(Items.PURPLE_DYE, 2),
        Map.entry(Items.BLUE_DYE, 2),
        Map.entry(Items.BROWN_DYE, 2),
        Map.entry(Items.GREEN_DYE, 2),
        Map.entry(Items.RED_DYE, 2),
        Map.entry(Items.BLACK_DYE, 2),
        Map.entry(Items.DANDELION, 1),
        Map.entry(Items.POPPY, 1),
        Map.entry(Items.BLUE_ORCHID, 2),
        Map.entry(Items.ALLIUM, 2),
        Map.entry(Items.AZURE_BLUET, 2),
        Map.entry(Items.RED_TULIP, 2),
        Map.entry(Items.ORANGE_TULIP, 2),
        Map.entry(Items.WHITE_TULIP, 2),
        Map.entry(Items.PINK_TULIP, 2),
        Map.entry(Items.OXEYE_DAISY, 2),
        Map.entry(Items.SUNFLOWER, 2),
        Map.entry(Items.LILAC, 2),
        Map.entry(Items.ROSE_BUSH, 2),
        Map.entry(Items.PEONY, 2),
        Map.entry(Items.CORNFLOWER, 2),
        Map.entry(Items.LILY_OF_THE_VALLEY, 2),
        Map.entry(Items.WITHER_ROSE, 3),
        Map.entry(Items.TORCHFLOWER, 2),
        Map.entry(Items.CANDLE, 2),
        Map.entry(Items.WHITE_CANDLE, 2),
        Map.entry(Items.ORANGE_CANDLE, 2),
        Map.entry(Items.MAGENTA_CANDLE, 2),
        Map.entry(Items.LIGHT_BLUE_CANDLE, 2),
        Map.entry(Items.YELLOW_CANDLE, 2),
        Map.entry(Items.LIME_CANDLE, 2),
        Map.entry(Items.PINK_CANDLE, 2),
        Map.entry(Items.GRAY_CANDLE, 2),
        Map.entry(Items.LIGHT_GRAY_CANDLE, 2),
        Map.entry(Items.CYAN_CANDLE, 2),
        Map.entry(Items.PURPLE_CANDLE, 2),
        Map.entry(Items.BLUE_CANDLE, 2),
        Map.entry(Items.BROWN_CANDLE, 2),
        Map.entry(Items.GREEN_CANDLE, 2),
        Map.entry(Items.RED_CANDLE, 2),
        Map.entry(Items.BLACK_CANDLE, 2),
        Map.entry(Items.OAK_PLANKS, 1),
        Map.entry(Items.SPRUCE_PLANKS, 1),
        Map.entry(Items.BIRCH_PLANKS, 1),
        Map.entry(Items.JUNGLE_PLANKS, 1),
        Map.entry(Items.ACACIA_PLANKS, 1),
        Map.entry(Items.DARK_OAK_PLANKS, 1),
        Map.entry(Items.MANGROVE_PLANKS, 1),
        Map.entry(Items.CHERRY_PLANKS, 1),
        Map.entry(Items.PALE_OAK_PLANKS, 1),
        Map.entry(Items.STICK, 1),
        Map.entry(Items.BOWL, 1),
        Map.entry(Items.SOUL_SOIL, 2),
        Map.entry(Items.WARPED_HYPHAE, 2),
        Map.entry(Items.CRIMSON_HYPHAE, 2),
        Map.entry(Items.DEAD_TUBE_CORAL, 1),
        Map.entry(Items.DEAD_BRAIN_CORAL, 1),
        Map.entry(Items.DEAD_BUBBLE_CORAL, 1),
        Map.entry(Items.DEAD_FIRE_CORAL, 1),
        Map.entry(Items.DEAD_HORN_CORAL, 1),

        // --- Tier 3: Uncommon (4–10 coins) - Requires Stone+ Tools or Hunting ---
        Map.entry(Items.QUARTZ, 4),
        Map.entry(Items.REDSTONE, 4),
        Map.entry(Items.CHORUS_FRUIT, 4),
        Map.entry(Items.BONE, 3),
        Map.entry(Items.STRING, 3),
        Map.entry(Items.SPIDER_EYE, 4),
        Map.entry(Items.INK_SAC, 4),
        Map.entry(Items.GUNPOWDER, 5),
        Map.entry(Items.SLIME_BALL, 5),
        Map.entry(Items.MAGMA_CREAM, 6),
        Map.entry(Items.GLOWSTONE_DUST, 5),
        Map.entry(Items.OBSIDIAN, 6),
        Map.entry(Items.CRYING_OBSIDIAN, 8),
        Map.entry(Items.SEA_PICKLE, 3),
        Map.entry(Items.PRISMARINE_SHARD, 4),
        Map.entry(Items.WET_SPONGE, 4),
        Map.entry(Items.TUBE_CORAL, 2),
        Map.entry(Items.BRAIN_CORAL, 2),
        Map.entry(Items.BUBBLE_CORAL, 2),
        Map.entry(Items.FIRE_CORAL, 2),
        Map.entry(Items.HORN_CORAL, 2),
        Map.entry(Items.LEATHER, 5),
        Map.entry(Items.FEATHER, 3),
        Map.entry(Items.RABBIT_HIDE, 3),
        Map.entry(Items.HONEY_BOTTLE, 4),
        Map.entry(Items.RABBIT_FOOT, 6),
        Map.entry(Items.ARMADILLO_SCUTE, 3),
        Map.entry(Items.MILK_BUCKET, 4),
        Map.entry(Items.BOOK, 5),

        // --- Tier 4: Rare (12–35 coins) - Requires Iron+ Tools or Significant Effort ---
        Map.entry(Items.LAPIS_LAZULI, 8),
        Map.entry(Items.EMERALD, 10),
        Map.entry(Items.AMETHYST_SHARD, 7),
        Map.entry(Items.RAW_COPPER, 5),
        Map.entry(Items.COPPER_INGOT, 8),
        Map.entry(Items.RAW_IRON, 10),
        Map.entry(Items.IRON_INGOT, 14),
        Map.entry(Items.RAW_GOLD, 12),
        Map.entry(Items.GOLD_INGOT, 18),
        Map.entry(Items.GLOWSTONE, 10),
        Map.entry(Items.REDSTONE_BLOCK, 20),
        Map.entry(Items.PRISMARINE_CRYSTALS, 6),
        Map.entry(Items.PRISMARINE_SHARD, 4),
        Map.entry(Items.DARK_PRISMARINE, 12),
        Map.entry(Items.SPONGE, 8),
        Map.entry(Items.TURTLE_SCUTE, 8),
        Map.entry(Items.GLOW_INK_SAC, 10),
        Map.entry(Items.PHANTOM_MEMBRANE, 12),
        Map.entry(Items.WRITABLE_BOOK, 8),
        Map.entry(Items.SADDLE, 18),
        Map.entry(Items.NAME_TAG, 25),
        Map.entry(Items.LEAD, 10),

        // --- Tier 5: Very Rare (30–60 coins) - Diamond tier, Boss Drops, Nether Difficulty ---
        Map.entry(Items.DIAMOND, 35),
        Map.entry(Items.COPPER_BLOCK, 24),
        Map.entry(Items.IRON_BLOCK, 50),
        Map.entry(Items.GOLD_BLOCK, 70),
        Map.entry(Items.BLAZE_ROD, 25),
        Map.entry(Items.CREEPER_HEAD, 35),
        Map.entry(Items.ZOMBIE_HEAD, 35),
        Map.entry(Items.SKELETON_SKULL, 35),

        // --- Tier 6: Extremely Rare (80–200 coins) - End-game, Boss Exclusive ---
        Map.entry(Items.DIAMOND_BLOCK, 140),
        Map.entry(Items.ENDER_PEARL, 40),
        Map.entry(Items.ECHO_SHARD, 60),
        Map.entry(Items.NETHERITE_SCRAP, 80),
        Map.entry(Items.SHULKER_SHELL, 100),
        Map.entry(Items.WITHER_SKELETON_SKULL, 80),
        Map.entry(Items.PLAYER_HEAD, 150),

        // --- Tier 7: Legendary (300–600 coins) - One-of-a-kind/Boss-only ---
        Map.entry(Items.NETHERITE_INGOT, 350),
        Map.entry(Items.NETHER_STAR, 500),
        Map.entry(Items.DRAGON_EGG, 1000)
    );

    private ItemSellPriceRegistry() {}
}
